"""Add disabled fix  field to users

Revision ID: 7c06030f5e89
Revises: a470df22b3a1
Create Date: 2026-02-03 18:55:36.480194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c06030f5e89'
down_revision: Union[str, Sequence[str], None] = 'a470df22b3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_column('users', 'disable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###
