"""Add disabled field to users

Revision ID: a470df22b3a1
Revises: c50a947e2842
Create Date: 2026-02-03 18:52:45.419515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a470df22b3a1'
down_revision: Union[str, Sequence[str], None] = 'c50a947e2842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disable')
    # ### end Alembic commands ###
